<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    <script>
    /* 
    Promise.all()方法用于将多个 Promise 实例，包装成一个新的 Promise 实例。
    
    
    
    
     */


        let {
            log
        } = console;
        const promises = [2, 3, 5, 7, 11, 13].map(function (item) {
            return Promise.resolve(item)
        });
        log(promises)
        log(Promise.all(promises))
        Promise.all(promises).then(function (posts) {
            console.log(posts)//[2,3,5,7,11,13]
        }).catch(function (reason) {
            console.log(reason)
        });

     /* Promise.all()方法接受一个数组作为参数，p1、p2、p3都是 Promise 实例
     
     ps的状态由p1、p2、p3决定，分成两种情况。

    （1）只有p1、p2、p3的状态都变成fulfilled，ps的状态才会变成fulfilled，此时p1、p2、p3的返回值组成一个数组，传递给p的回调函数。

    （2）只要p1、p2、p3之中有一个被rejected，ps的状态就变成rejected，此时第一个被reject的实例的返回值，会传递给ps的回调函数。

    （3）如果作为参数的 Promise 实例，自己定义了catch方法，那么它一旦被rejected，并不会触发Promise.all()的catch方法。
     
      */

        const p1 = new Promise((res, rej) => {
            setTimeout(() => {
                res(1)
            }, 1000)
        })
        const p2 = new Promise((res, rej) => {
            setTimeout(() => {
               res('err 2')
            }, 2000)
        })
        const p3 = new Promise((res, rej) => {
            setTimeout(() => {
                rej(3)
            }, 3000)
        }).catch(function(x){
           console.log(x)//3
           return "错误"
        })
        let ps = [p1,p2,p3]
        Promise.all(ps).then(function(x){
            log(x)//[1,"err 2","错误"]
        }).catch(function(x){
          log(x)
        })
        log( Promise.all(ps))
    </script>
</body>

</html>